<?php

$wppg_currency = array( 'United Arab Emirates Dirham' => array( 'currency_name' => 'United Arab Emirates Dirham', 'currency_symbol' => 'د.إ' ),
    'Australian Dollars' => array( 'currency_name' => 'Australian Dollars', 'currency_symbol' => '$' ),
    'Brazilian Real' => array( 'currency_name' => 'Brazilian Real', 'currency_symbol' => 'R$' ),
    'Bulgarian Lev' => array( 'currency_name' => 'Bulgarian Lev', 'currency_symbol' => 'лв.' ),
    'Canadian Dollars' => array( 'currency_name' => 'Canadian Dollars', 'currency_symbol' => '$' ),
    'Chilean Peso' => array( 'currency_name' => 'Chilean Peso', 'currency_symbol' => '$' ),
    'Chinese Yuan' => array( 'currency_name' => 'Chinese Yuan', 'currency_symbol' => '¥' ),
    'Czech Koruna' => array( 'currency_name' => 'Czech Koruna', 'currency_symbol' => 'Kč' ),
    'Danish Krone' => array( 'currency_name' => 'Danish Krone', 'currency_symbol' => 'kr' ),
    'Euros' => array( 'currency_name' => 'Euros', 'currency_symbol' => '€' ),
    'Hong Kong Dollar' => array( 'currency_name' => 'Hong Kong Dollar', 'currency_symbol' => '$' ),
    'Croatia kuna' => array( 'currency_name' => 'Croatia kuna', 'currency_symbol' => 'Kn' ),
    'Hungarian Forint' => array( 'currency_name' => 'Hungarian Forint', 'currency_symbol' => 'Ft' ),
    'Icelandic krona' => array( 'currency_name' => 'Icelandic krona', 'currency_symbol' => 'Kr.' ),
    'Indonesia Rupiah' => array( 'currency_name' => 'Indonesia Rupiah', 'currency_symbol' => 'Rp' ),
    'Indian Rupee' => array( 'currency_name' => 'Indian Rupee ', 'currency_symbol' => 'Rs.' ),
    'Israeli Shekel' => array( 'currency_name' => 'Israeli Shekel', 'currency_symbol' => '₪' ),
    'Japanese Yen' => array( 'currency_name' => 'Japanese Yen', 'currency_symbol' => '¥' ),
    'South Korean Won' => array( 'currency_name' => 'South Korean Won', 'currency_symbol' => '₩' ),
    'Malaysian Ringgits' => array( 'currency_name' => 'Malaysian Ringgits', 'currency_symbol' => 'RM' ),
    'Mexican Peso' => array( 'currency_name' => 'Mexican Peso', 'currency_symbol' => '$' ),
    'Nigerian Naira' => array( 'currency_name' => 'Nigerian Naira', 'currency_symbol' => '₦' ),
    'Norwegian Krone' => array( 'currency_name' => 'Norwegian Krone', 'currency_symbol' => 'kr' ),
    'New Zealand Dollar' => array( 'currency_name' => 'New Zealand Dollar', 'currency_symbol' => '$' ),
    'Philippine Pesos' => array( 'currency_name' => 'Philippine Pesos', 'currency_symbol' => '₱' ),
    'Pounds Sterling' => array( 'currency_name' => 'Pounds Sterling', 'currency_symbol' => '£' ),
    'Romanian Leu' => array( 'currency_name' => 'Romanian Leu', 'currency_symbol' => 'lei' ),
    'Russian Ruble' => array( 'currency_name' => 'Russian Ruble', 'currency_symbol' => 'руб.' ),
    'Singapore Dollar' => array( 'currency_name' => 'Singapore Dollar', 'currency_symbol' => '$' ),
    'South African rand' => array( 'currency_name' => 'South African rand ', 'currency_symbol' => 'R' ),
    'Swedish Krona' => array( 'currency_name' => 'Swedish Krona', 'currency_symbol' => 'kr' ),
    'Swiss Franc' => array( 'currency_name' => 'Swiss Franc', 'currency_symbol' => 'CHF' ),
    'Taiwan New Dollars' => array( 'currency_name' => 'Bulgarian Lev', 'currency_symbol' => 'NT$' ),
    'Thai Baht' => array( 'currency_name' => 'Thai Baht', 'currency_symbol' => '฿' ),
    'Turkish Lira' => array( 'currency_name' => 'Turkish Lira', 'currency_symbol' => 'TL' ),
    'US Dollars' => array( 'currency_name' => 'US Dollars', 'currency_symbol' => '$' ),
    'Vietnamese Dong' => array( 'currency_name' => 'Vietnamese Dong', 'currency_symbol' => '₫' )
);
